language: php

php:
  - 5.4

services:
  - mysql

before_script:
  - mysql -e 'create database torii_testing;'

before_script:
  - ant -Djslint.enabled=false -Dcommons.env=testing db:initialize

script: ant -Djslint.enabled=false
